### ISSUE TITLE
Request: fp16 inference

### ISSUE THREAD

**Issue by styler00dollar** [hyw-dev/GMFSS#1]
This repository is amazing, I really like the results, but the vram usage is quite high when I try to use it with vapoursynth. 512x512px needs around 15gb VRAM with a real video. The speed is not bad, but I struggle to get some sort of usable resolution. For some reason with your `test.py` it needs much less vram. When I try to use the model class directly, for some reason it needs a lot more memory.

When i use `test.py` with a loop and also 512x512:
```python
from tqdm import tqdm
for i in tqdm(range(1000)):
  result = make_inference(I0, I1, n_frames, scale, pred_bidir_flow)
```
![image](https://user-images.githubusercontent.com/51405565/190707462-f453c7dd-d04e-4e28-a679-9b0b2ca6d7e7.png)

---

```python 
class Model_inference(nn.Module):
    def __init__(self):
        super(Model_inference, self).__init__()
        self.model = Model()

    def forward(self, I0, I1):
        n_frames = 1
        scale = 1.0  # flow scale
        timesteps = [i / (n_frames + 1) for i in range(1, n_frames + 1)]

        # padding frames
        n, c, h, w = I0.shape
        tmp = max(32, int(32 / scale))
        ph = ((h - 1) // tmp + 1) * tmp
        pw = ((w - 1) // tmp + 1) * tmp
        padding = (0, pw - w, 0, ph - h)
        I0 = F.pad(I0, padding)
        I1 = F.pad(I1, padding)        
        return self.model.inference(I0, I1, timesteps, scale, pred_bidir_flow=False)[0][:h, :w, :]


model = Model_inference()
model.eval().cuda()

test_input = torch.rand(1,3,720,1280).cuda()

out = model(test_input, test_input)
print(out.shape)


from tqdm import tqdm
for i in tqdm(range(1000)):
  out = model(test_input, test_input)
```

![image](https://user-images.githubusercontent.com/51405565/190703534-daa6a36a-4764-4612-9b76-75e11955b32b.png)

720p is not possible.
![image](https://user-images.githubusercontent.com/51405565/190703347-fd63cbd2-3e94-4a0b-a8a8-141b76b6975a.png)

512x512 is the highest i can do with vapoursynth for now.
![image](https://user-images.githubusercontent.com/51405565/190702182-4008d576-7985-4f85-a614-2d2de02c2630.png)

I tried to add fp16 a bit but I didn't get far yet. With fp16 it should use a lot less vram.

```python
import itertools
import numpy as np
import vapoursynth as vs
import functools
from pytorch_msssim import ssim, ms_ssim, SSIM, MS_SSIM

import torch 
device = torch.device("cuda")
torch.set_grad_enabled(False)
torch.backends.cudnn.enabled = True
torch.backends.cudnn.benchmark = True

def make_inference(model, I0, I1, n, scale, pred_bidir_flow=False):
    timesteps = [i / (n + 1) for i in range(1, n + 1)]
    return model.inference(I0, I1, timesteps, scale, pred_bidir_flow)

# https://github.com/HolyWu/vs-rife/blob/master/vsrife/__init__.py
def GMFSS(
    clip: vs.VideoNode,
    fp16: bool = True,
) -> vs.VideoNode:

    core = vs.core
    from .GMFSS_arch import Model
    import torch

    n_frames = 1
    scale = 1.0  # flow scale
    pred_bidir_flow = False  # Estimate bilateral optical flow at once (accelerate)

    device = torch.device("cuda")
    torch.set_grad_enabled(False)
    torch.backends.cudnn.enabled = True
    torch.backends.cudnn.benchmark = True

    model = Model()
    model.load_model("/workspace/tensorrt/VSGAN-tensorrt-docker/weights/", -1)
    model.eval()
    model.device("cuda")

    w = clip.width
    h = clip.height
    scale_list = [8 / scale, 4 / scale, 2 / scale, 1 / scale]


    def frame_to_tensor(frame: vs.VideoFrame):
        return np.stack(
            [np.asarray(frame[plane]) for plane in range(frame.format.num_planes)]
        )

    def tensor_to_frame(f: vs.VideoFrame, array) -> vs.VideoFrame:
        for plane in range(f.format.num_planes):
            d = np.asarray(f[plane])
            np.copyto(d, array[plane, :, :])
        return f

    def tensor_to_clip(clip: vs.VideoNode, image) -> vs.VideoNode:
        clip = core.std.BlankClip(
            clip=clip, width=image.shape[-1], height=image.shape[-2]
        )
        return core.std.ModifyFrame(
            clip=clip,
            clips=clip,
            selector=lambda n, f: tensor_to_frame(f.copy(), image),
        )

    def execute(n: int, clip: vs.VideoNode) -> vs.VideoNode:
        if (
            (n % 2 == 0)
            or n == 0
            or n in skip_framelist
            or n == clip.num_frames - 1
        ):
            return clip

        I0 = frame_to_tensor(clip.get_frame(n - 1))
        I1 = frame_to_tensor(clip.get_frame(n + 1))

        I0 = torch.Tensor(I0).unsqueeze(0).to("cuda", non_blocking=True)
        I1 = torch.Tensor(I1).unsqueeze(0).to("cuda", non_blocking=True)
        middle = make_inference(model, I0, I1, n_frames, scale, pred_bidir_flow)[0]
        middle = middle.swapaxes(0, 2).swapaxes(1, 2)/255

        return tensor_to_clip(clip=clip, image=middle)

    clip = core.std.Interleave([clip, clip])
    return core.std.FrameEval(
        core.std.BlankClip(clip=clip, width=clip.width, height=clip.height),
        functools.partial(execute, clip=clip),
    )
```
I can't figure out why your `test.py` needs less vram.

Update: 
Right after writing this I figured out that 
```python
torch.set_grad_enabled(False)
torch.backends.cudnn.enabled = True
torch.backends.cudnn.benchmark = True
```
decreases vram usage a lot, leaving it here in case someone else will run into it. Sadly it does not in my vapoursynth script. My request for fp16 is still valid though.

Update2:
After a lot of trying I figured out that 
```
with torch.inference_mode():
```
does the job as well, and uses even less vram than `torch.backends.cudnn`.

**Comment by routineLife1** [comment]
sorry for replying so late, actually, I don't have a good way to implement fp16, because some gmflow operators cannot use half precision. thanks for the update2, it really works.
I'll take some more time to find the effective way of decrasing vram usage, if it works, I'll update the code soon.

**Comment by styler00dollar** [comment]
Thanks for taking vram usage into consideration. At least 720p seems to be doable with ~10gb vram with inference_mode in my vapoursynth code.

**Comment by YiWeiHuang-stack** [comment]
I think the memory usage of pytorch is dynamically allocated，gpu with different memory capacity may occupy different，
on my 3070laptop, 720p just need ~6gb vram with inference_mode.

**Comment by routineLife1** [comment]
I updated the code of FusionNet，it seems to use a lot less vram.

**Comment by styler00dollar** [comment]
Need to test it later, thanks. One suggestion would be, if everything in fp16 is not possible, to allow inference with partial fp16 and do it where it is possible.

**Comment by routineLife1** [comment]
It is recommended that you try gmfupss based on gmfss, which use a lot less vram and faster (1080P 4.4G,5.00frames/s on my 3070laptop) 
https://github.com/98mxr/GMFupSS

**Comment by styler00dollar** [comment]
I tested gmfupss and indeed, it seems very good. Thanks for the suggestion. On my 1070ti with vapoursynth and ffmpeg while doing 2x with inference mode:
720p: 3664mb / 3.6fps
1080p: 6496mb / 1fps
![usage](https://user-images.githubusercontent.com/51405565/190899720-88eff156-5463-4b7e-a172-3195195cc4c8.png)

**Comment by styler00dollar** [comment]
I tried to add fp16 to parts of the [GMFupSS network](https://github.com/styler00dollar/VSGAN-tensorrt-docker/blob/main/src/GMFupSS_arch.py) and I had up to 77% speed improvement while also looking very similar to fp32. Maybe it is possible to use fp16 in more places, but I am quite happy for now. I guess this issue can be closed if the cupy code will stay at fp32.
![grafik](https://user-images.githubusercontent.com/51405565/197640123-a09d92ef-9556-4288-9fdd-c0f17b0517bc.png)

**Comment by routineLife1** [comment]
Thank you for optimizing GMFupSS, and it is recommended to check out our new project [GMFSS_union](https://github.com/98mxr/GMFSS_union) which performes better than gmfss and GMFupSS

**Comment by mikebilly** [comment]
@hyw-dev thanks for the project GMFSS_union. For anime interpolation, which one creates the best results, vanillagan or wgan?

**Comment by routineLife1** [comment]
Thank you for your attention to this project, vanillagan is blurrier than the wgan, but it looks more stable and less color deviation. In general, the performance of the two models is very similar

**Comment by mikebilly** [comment]
@hyw-dev thanks for your reply, so I guess I should use wgan then. Btw there is this project https://github.com/lllyasviel/ToonDecompose that separates the video into different sprites, do you think it would help in video interpolation where it could interpolate each sprite seperately and add everything afterwards?

**Comment by routineLife1** [comment]
> @hyw-dev thanks for your reply, so I guess I should use wgan then. Btw there is this project https://github.com/lllyasviel/ToonDecompose that separates the video into different sprites, do you think it would help in video interpolation where it could interpolate each sprite seperately and add everything afterwards?

separates the animation into foreground and background may help to solve the occlusion problem,so i believe it could improve 
the quality of intermediate frame, and you can also interpolate only the background and not the anime characters, so as to avoid the destruction of the character frame.

**Comment by routineLife1** [comment]
@mikebilly i just tested the ToonDecompose, but the speed is very slow (over 1 hour, 3070laptop) and results seems not good enough, only few simple scene could works well. separates the video into different sprites is a good idea, but only if it could be more accurate.

**Comment by mikebilly** [comment]
@hyw-dev yep, I agree it's a good idea to separate the video into different sprites. It shall be more accurate in the future I guess. How about using your own flow estimates to separate sprites?

**Comment by routineLife1** [comment]
gmflow with refinement(sintel) may perform better then RAFT-sintel, so, using this flow estimates to separate sprites may improve the result, I thought.
